name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: docker:19.03.12

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
      # Your workflow steps here

      # - name: Checkout Repository
      #   uses: actions/checkout@v2
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      
      # - name: Build Frontend Docker Image
      #   run: docker build -t yourusername/frontend:latest mern-docker/frontend
      
      # - name: Build Backend Docker Image
      #   run: docker build -t yourusername/backend:latest mern-docker/backend
      
      - name: SSH into Server and Push Docker Images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo 'hi'
          # script: |
          #   docker tag frontend:latest ${{ secrets.SERVER_HOST }}/frontend:latest
          #   docker tag backend:latest ${{ secrets.SERVER_HOST }}/backend:latest
          #   docker push ${{ secrets.SERVER_HOST }}/frontend:latest
          #   docker push ${{ secrets.SERVER_HOST }}/backend:latest
