name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Frontend Docker Image
        run: docker build -t yourusername/frontend:latest frontend-directory
      
      - name: Build Backend Docker Image
        run: docker build -t yourusername/backend:latest backend-directory
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Frontend Docker Image
        run: docker push yourusername/frontend:latest
      
      - name: Push Backend Docker Image
        run: docker push yourusername/backend:latest
      
      - name: SSH into Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull yourusername/frontend:latest
            docker pull yourusername/backend:latest
            docker-compose up -d
