name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Frontend Docker Image
        run: docker build -t yourusername/frontend:latest frontend-directory
      
      - name: Build Backend Docker Image
        run: docker build -t yourusername/backend:latest backend-directory
      
      - name: SSH into Server and Push Docker Images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker login -u ${{ secrets.SERVER_DOCKER_USERNAME }} -p ${{ secrets.SERVER_DOCKER_PASSWORD }} ${{ secrets.SERVER_REGISTRY }}
            docker tag yourusername/frontend:latest ${{ secrets.SERVER_REGISTRY }}/yourusername/frontend:latest
            docker tag yourusername/backend:latest ${{ secrets.SERVER_REGISTRY }}/yourusername/backend:latest
            docker push ${{ secrets.SERVER_REGISTRY }}/yourusername/frontend:latest
            docker push ${{ secrets.SERVER_REGISTRY }}/yourusername/backend:latest
